"""Constants used by the client for the various releases to help the developer
stay up with Blizzard's naming conventions for the various classics"""

VANC = "classic1x"
TBCC = "classic"
RETAIL = "retail"

# MODULES = {
#     "classic1x": (
#         "connected_realm",
#         "creature",
#         "guild",
#         "item",
#         "playable_class",
#         "playable_race",
#         "power",
#         "realm",
#         "region",
#         "wow_token",
#     ),
#     "classic": (
#         "auction",
#         "connected_realm",
#         "creature",
#         "guild",
#         "item",
#         "media",
#         "playable_class",
#         "playable_race",
#         "power",
#         "pvp",
#         "realm",
#         "region",
#         "wow_token",
#     ),
#     "retail": (
#         "achievement",
#         "account",
#         "auction",
#         "azerite",
#         "character",
#         "connected_realm",
#         "covenant",
#         "creature",
#         "guild",
#         "item",
#         "journal",
#         "media",
#         "modcraft",
#         "mount",
#         "mythic_plus",
#         "mythic_raid",
#         "pet",
#         "playable_class",
#         "playable_race",
#         "playable_spec",
#         "power",
#         "profession",
#         "pvp",
#         "quest",
#         "realm",
#         "region",
#         "reputation",
#         "spell",
#         "talent",
#         "tech_talent",
#         "title",
#         "wow_token",
#     ),
# }

MODULES = {
    "classic1x": {
        "game_data": (
            "ConnectedRealm",
            "Creature",
            "GuildCrest",
            "Item",
            "PlayableClass",
            "PlayableRace",
            "Power",
            "Realm",
            "Region",
            "WoWToken",
        )
    },
    "classic": {
        "game_data": (
            "Auction",
            "ConnectedRealm",
            "Creature",
            "GuildCrest",
            "Item",
            "media",
            "PlayableClass",
            "PlayableRace",
            "Power",
            "PvPSeason",
            "Realm",
            "Region",
            "WoWToken",
        ),
    },
    "retail": {
        "game_data": (
            "Achievement",
            "Auction",
            "Azerite",
            "ConnectedRealm",
            "Covenant",
            "Creature",
            "GuildCrest",
            "Item",
            "Journal",
            "Media",
            "ModifiedCrafting",
            "Mount",
            "MythicKeystoneAffix",
            "MythicKeystoneDungeon",
            "MythicKeystoneLeaderboard",
            "MythicRaid",
            "Pet",
            "PlayableClass",
            "PlayableRace",
            "PlayableSpec",
            "Power",
            "Profession",
            "PvPSeason",
            "PvPTier",
            "Quest",
            "Realm",
            "Region",
            "Reputation",
            "Spell",
            "Talent",
            "TechTalent",
            "Title",
            "WoWToken",
        ),
        "profile": (
            "Account",
            "CharacterAchievements",
            "CharacterAppearance",
            "CharacterCollections",
            "CharacterEncounters",
            "CharacterEquipment",
            "CharacterHunterPets",
            "CharacterMedia",
            "CharacterMythicKeystone",
            "CharacterProfessions",
            "CharacterProfile",
            "CharacterPVP",
            "CharacterQuests",
            "CharacterSoulBinds",
            "CharacterSpecializations",
            "CharacterStatistics",
            "CharacterTitles",
            "Guild",
        ),
    },
}
