"""Constants used by the client for the various releases to help the developer
stay up with Blizzard's naming conventions for the various classics"""

VANC = "classic1x"
TBCC = "classic"
RETAIL = "retail"

MODULES = {
    "classic1x": (
        "connected_realm",
        "creature",
        "guild",
        "item",
        "playable_class",
        "playable_race",
        "power",
        "realm",
        "region",
        "wow_token",
    ),
    "classic": (
        "auction",
        "connected_realm",
        "creature",
        "guild",
        "item",
        "media",
        "playable_class",
        "playable_race",
        "power",
        "pvp",
        "realm",
        "region",
        "wow_token",
    ),
    "retail": (
        "achievement",
        "account",
        "auction",
        "azerite",
        "character",
        "connected_realm",
        "covenant",
        "creature",
        "guild",
        "item",
        "journal",
        "media",
        "modcraft",
        "mount",
        "mythic_plus",
        "mythic_raid",
        "pet",
        "playable_class",
        "playable_race",
        "playable_spec",
        "power",
        "profession",
        "pvp",
        "quest",
        "realm",
        "region",
        "reputation",
        "spell",
        "talent",
        "tech_talent",
        "title",
        "wow_token",
    ),
}

# MODULES = {
#     "classic1x": (
#         "game_data.connected_realm",
#         "creature",
#         "guild",
#         "item",
#         "playable_class",
#         "playable_race",
#         "power",
#         "realm",
#         "region",
#         "wow_token",
#     ),
#     "classic": (
#         "auction",
#         "connected_realm",
#         "creature",
#         "guild",
#         "item",
#         "media",
#         "playable_class",
#         "playable_race",
#         "power",
#         "pvp",
#         "realm",
#         "region",
#         "wow_token",
#     ),
#     "retail": (
#         "achievement",
#         "account",
#         "auction",
#         "azerite",
#         "character",
#         "connected_realm",
#         "covenant",
#         "creature",
#         "guild",
#         "item",
#         "journal",
#         "media",
#         "modcraft",
#         "mount",
#         "mythic_plus",
#         "mythic_raid",
#         "pet",
#         "playable_class",
#         "playable_race",
#         "playable_spec",
#         "power",
#         "profession",
#         "pvp",
#         "quest",
#         "realm",
#         "region",
#         "reputation",
#         "spell",
#         "talent",
#         "tech_talent",
#         "title",
#         "wow_token",
#     ),
# }
